version: '3.8'

services:
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:8000 app:app
    expose:
      - 8000
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=8000
      - FLASK_ENV=development
      - DB_HOST=postgresql://user:pass@db:5432/database
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web