version: '3.8'

services:
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:8000 app:app
    expose:
      - 8000
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=8000
      - FLASK_ENV=development
      - DB_HOST=postgresql://user:pass@postgres:5432/database
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data: